name: "Docs"

on:
  push:
    branches:
      - 'main'
    tags: ['*']

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - uses: abatilo/actions-poetry@v2
      with:
          poetry-version: "1.2"

    - name: Install Deps
      run: poetry install

    - name: Build docs
      run: poetry run make -C docs/ html

    - name: Commit documentation changes
      run: |
        git clone https://github.com/quantaser/pytemplate.git --branch gh-pages --single-branch gh-pages
        rm -rf gh-pages/*
        touch gh-pages/.nojekyll
        cp -r docs/build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore the return code.

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
