name: "Docs"

on:
  push:
    branches:
      - '*'
    tags: ['*']
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - uses: abatilo/actions-poetry@v2

    - name: Install Deps
      run: poetry install

    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "pip install sphinx_rtd_theme"

    - name: Commit documentation changes
      run: |
        git clone https://github.com/quantaser/pytemplate.git --branch gh-pages --single-branch gh-pages
        rm -rf gh-pages/*
        touch gh-pages/.nojekyll
        cp -r docs/build/html/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore the return code.

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
